import Link from "next/link";
import { ArrowRight, Cloud, ExternalLink, Globe2, Settings2, ShieldCheck, Store } from "lucide-react";
import type { Tenant } from "@/lib/db/schema";
import { listTenantProducts } from "@/lib/tenant-firestore";
import { TenantProductBuilder } from "@/components/admin/TenantProductBuilder";

export async function TenantAdminWorkspace({ tenant, firestoreConnected }: { tenant: Tenant; firestoreConnected: boolean }) {
  const products = firestoreConnected ? await listTenantProducts(tenant.id, { includeDrafts: true }).catch(() => []) : [];
  return <div className="mx-auto max-w-[1200px] space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-[#f3eadb] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.18em] text-[#9b682d]"><Store className="h-3.5 w-3.5" /> Subscriber workspace</div><h1 className="font-display text-3xl font-bold tracking-tight">{tenant.name} admin</h1><p className="mt-1 text-sm text-black/50">Real workspace operations, scoped to {tenant.slug}.</p></div><div className="flex flex-wrap gap-2"><Link href={`/platform/stores/${tenant.slug}`} className="inline-flex items-center gap-2 rounded-xl border border-black/10 bg-white px-3.5 py-2.5 text-sm font-bold transition hover:border-black/30"><Settings2 className="h-4 w-4" /> Workspace setup</Link><Link href={`/store/${tenant.slug}`} target="_blank" className="inline-flex items-center gap-2 rounded-xl bg-[#11110f] px-3.5 py-2.5 text-sm font-bold text-white transition hover:bg-black"><ExternalLink className="h-4 w-4" /> View store</Link></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-black/10 bg-white p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-black/40"><Cloud className="h-4 w-4" /> Database</div><div className="mt-4 text-lg font-bold">{firestoreConnected ? "Connected" : "Not connected"}</div><div className="mt-1 text-xs text-black/45">Workspace Firestore</div></div><div className="rounded-2xl border border-black/10 bg-white p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-black/40"><Store className="h-4 w-4" /> Catalogue</div><div className="mt-4 text-lg font-bold">{products.length} products</div><div className="mt-1 text-xs text-black/45">Live workspace records</div></div><div className="rounded-2xl border border-black/10 bg-white p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-black/40"><Globe2 className="h-4 w-4" /> Public site</div><div className="mt-4 text-lg font-bold">{tenant.status === "active" ? "Live" : "Setup"}</div><div className="mt-1 text-xs text-black/45">{tenant.slug}.aurelia.app</div></div></div>
    {!firestoreConnected ? <div className="rounded-[22px] border border-amber-200 bg-amber-50 p-5"><div className="flex items-start gap-3"><Cloud className="mt-0.5 h-5 w-5 shrink-0 text-amber-700" /><div><h2 className="font-bold text-amber-900">Connect Firestore to unlock your admin data.</h2><p className="mt-1 text-sm leading-6 text-amber-800/70">Aurelia never falls back to another subscriber’s data. Connect and test your database from workspace setup, then this catalogue will write to your namespaced collection.</p><Link href={`/platform/stores/${tenant.slug}?step=database`} className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-amber-900 underline">Connect database <ArrowRight className="h-4 w-4" /></Link></div></div></div> : null}
    <TenantProductBuilder tenantId={tenant.id} tenantSlug={tenant.slug} products={products} connected={firestoreConnected} />
    <div className="flex items-center gap-2 rounded-2xl border border-black/10 bg-white px-4 py-3 text-xs text-black/45"><ShieldCheck className="h-4 w-4 text-emerald-600" /> Product writes are sent to this workspace’s Firestore only.</div>
  </div>;
}
